### ISSUE TITLE
Changing line width in GraphLayer does not work on all platforms

### ISSUE THREAD

**Issue by hpcowley** [iscoe/pytri#69]
According to the [three.js docs](https://threejs.org/docs/#api/materials/LineBasicMaterial.linewidth):
`Due to limitations in the ANGLE layer, with the WebGL renderer on Windows platforms linewidth will always be 1 regardless of the set value.`

Changing the linewidth in the graph layer does not render changes in Chrome, even on a Mac. A workaround may be changing LineBasicMaterial to [MeshLine](https://github.com/spite/THREE.MeshLine/blob/master/README.md)

**Comment by j6k4m8** [comment]
This is a known bug in WebGL ([reference](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/lineWidth)). Unfortunately, this is a `wontfix` because using a MeshLine costs us an enormous multiplier of render time. Would be happy to see a PR that adds an optional `use_meshline` bool arg, but it's low on the list of priorities for the project currently.

Do you have a use-case that makes this of particular or immediate import? 

Easiest solution is to just use Safari when you need thicc lines.

**Comment by hpcowley** [comment]
Had a use case, but just used Safari like you said. I'm ok not fixing!
